/**
 * CreateBoardDialog Component
 *
 * Dialog for creating a new Kanban board.
 * Uses BaseDialog for consistent modal behavior.
 * Allows user to enter name and optionally select a template for initial lists.
 */

import { useState } from 'react';
import { BaseDialog } from '../shared/dialogs/BaseDialog';
import { DEFAULT_BOARD_TEMPLATES } from '../../types/issueBoard';
import './CreateBoardDialog.css';

/**
 * @param {Object} props
 * @param {boolean} props.isOpen - Whether dialog is visible
 * @param {function} props.onClose - Callback to close dialog
 * @param {function} props.onCreate - Callback when board is created (boardData) => void
 * @param {boolean} props.saving - Whether a save operation is in progress
 */
export function CreateBoardDialog({ isOpen, onClose, onCreate, saving = false }) {
  const [name, setName] = useState('');
  const [template, setTemplate] = useState('kanban'); // 'empty' | 'kanban' | 'bugTriage'
  const [error, setError] = useState('');

  const handleSubmit = () => {
    // Validate
    const trimmedName = name.trim();
    if (!trimmedName) {
      setError('Please enter a board name');
      return;
    }

    // Get lists from template
    let lists = [];
    if (template !== 'empty' && DEFAULT_BOARD_TEMPLATES[template]) {
      lists = DEFAULT_BOARD_TEMPLATES[template].lists.map((list) => ({
        ...list,
        id: '', // Will be generated by the hook
      }));
    }

    // Create board data
    const boardData = {
      name: trimmedName,
      lists,
      showOthers: true,
      showClosed: true,
    };

    onCreate(boardData);
  };

  const handleClose = () => {
    setName('');
    setTemplate('kanban');
    setError('');
    onClose();
  };

  const footer = (
    <>
      <button
        type="button"
        className="dialog-btn dialog-btn-secondary"
        onClick={handleClose}
        disabled={saving}
      >
        Cancel
      </button>
      <button
        type="button"
        className="dialog-btn dialog-btn-primary"
        onClick={handleSubmit}
        disabled={saving}
      >
        {saving ? 'Creating...' : 'Create Board'}
      </button>
    </>
  );

  return (
    <BaseDialog
      isOpen={isOpen}
      onClose={handleClose}
      title="Create New Board"
      width={440}
      footer={footer}
      className="create-board-dialog"
    >
      {/* Name input */}
      <div className="dialog-form-group">
        <label htmlFor="board-name">Name</label>
        <input
          id="board-name"
          type="text"
          className={`dialog-input ${error ? 'error' : ''}`}
          value={name}
          onChange={(e) => {
            setName(e.target.value);
            setError('');
          }}
          placeholder="Enter board name..."
          disabled={saving}
          autoFocus
        />
        {error && <div className="dialog-error">{error}</div>}
      </div>

      {/* Template selection */}
      <div className="dialog-form-group">
        <label>Initial Lists</label>
        <div className="create-board-templates">
          <label className="create-board-template">
            <input
              type="radio"
              name="template"
              value="empty"
              checked={template === 'empty'}
              onChange={(e) => setTemplate(e.target.value)}
              disabled={saving}
            />
            <span className="template-label">Empty</span>
            <span className="template-description">
              Start with no lists (add later)
            </span>
          </label>

          <label className="create-board-template">
            <input
              type="radio"
              name="template"
              value="kanban"
              checked={template === 'kanban'}
              onChange={(e) => setTemplate(e.target.value)}
              disabled={saving}
            />
            <span className="template-label">To Do / In Progress / Done</span>
            <span className="template-description">
              Standard Kanban workflow with State labels
            </span>
          </label>

          <label className="create-board-template">
            <input
              type="radio"
              name="template"
              value="bugTriage"
              checked={template === 'bugTriage'}
              onChange={(e) => setTemplate(e.target.value)}
              disabled={saving}
            />
            <span className="template-label">Bug Triage</span>
            <span className="template-description">
              New / Confirmed / In Progress for bug tracking
            </span>
          </label>
        </div>
      </div>
    </BaseDialog>
  );
}
