/**
 * Azure DevOps Sample Data
 *
 * Simulates a realistic Azure DevOps portfolio with 100+ work items
 * across 4 sprints for a "Project Willow" mobile banking application.
 *
 * Hierarchy: Epic > Feature > User Story > Task/Bug
 * Team: 8 members, dates spanning Jan-May 2026
 */

// ============================================================================
// Team Members
// ============================================================================
const TEAM = [
  'alice.chen',
  'bob.martinez',
  'carol.wu',
  'david.kim',
  'elena.volkov',
  'frank.jones',
  'grace.patel',
  'henry.liu',
];

// ============================================================================
// Helper: date builder
// ============================================================================
function d(month, day) {
  return new Date(2026, month - 1, day, 12, 0, 0);
}

// ============================================================================
// Epics (Summary tasks, parent=0)
// ============================================================================
const epics = [
  {
    id: 1,
    text: 'Account Management',
    type: 'summary',
    parent: 0,
    start: d(1, 5),
    end: d(3, 20),
    progress: 65,
    open: true,
  },
  {
    id: 2,
    text: 'Payments & Transfers',
    type: 'summary',
    parent: 0,
    start: d(1, 12),
    end: d(4, 10),
    progress: 40,
    open: true,
  },
  {
    id: 3,
    text: 'Security & Authentication',
    type: 'summary',
    parent: 0,
    start: d(1, 5),
    end: d(3, 31),
    progress: 75,
    open: true,
  },
  {
    id: 4,
    text: 'Analytics & Reporting',
    type: 'summary',
    parent: 0,
    start: d(2, 2),
    end: d(4, 25),
    progress: 20,
    open: true,
  },
  {
    id: 5,
    text: 'Mobile Experience',
    type: 'summary',
    parent: 0,
    start: d(2, 16),
    end: d(5, 8),
    progress: 15,
    open: true,
  },
  {
    id: 6,
    text: 'Infrastructure & DevOps',
    type: 'summary',
    parent: 0,
    start: d(1, 5),
    end: d(5, 15),
    progress: 50,
    open: true,
  },
];

// ============================================================================
// Features (Summary tasks, parent=epic)
// ============================================================================
const features = [
  // Epic 1: Account Management
  {
    id: 10,
    text: 'User Registration Flow',
    type: 'summary',
    parent: 1,
    start: d(1, 5),
    end: d(2, 7),
    progress: 90,
    open: false,
  },
  {
    id: 11,
    text: 'Profile Management',
    type: 'summary',
    parent: 1,
    start: d(1, 19),
    end: d(2, 28),
    progress: 60,
    open: false,
  },
  {
    id: 12,
    text: 'Account Settings',
    type: 'summary',
    parent: 1,
    start: d(2, 9),
    end: d(3, 20),
    progress: 35,
    open: false,
  },

  // Epic 2: Payments & Transfers
  {
    id: 20,
    text: 'Internal Transfers',
    type: 'summary',
    parent: 2,
    start: d(1, 12),
    end: d(2, 21),
    progress: 80,
    open: false,
  },
  {
    id: 21,
    text: 'External Payments',
    type: 'summary',
    parent: 2,
    start: d(2, 2),
    end: d(3, 13),
    progress: 45,
    open: false,
  },
  {
    id: 22,
    text: 'Recurring Payments',
    type: 'summary',
    parent: 2,
    start: d(3, 2),
    end: d(4, 10),
    progress: 10,
    open: false,
  },

  // Epic 3: Security & Authentication
  {
    id: 30,
    text: 'Multi-Factor Authentication',
    type: 'summary',
    parent: 3,
    start: d(1, 5),
    end: d(2, 14),
    progress: 100,
    open: false,
  },
  {
    id: 31,
    text: 'Biometric Login',
    type: 'summary',
    parent: 3,
    start: d(1, 26),
    end: d(3, 6),
    progress: 70,
    open: false,
  },
  {
    id: 32,
    text: 'Session Management',
    type: 'summary',
    parent: 3,
    start: d(2, 16),
    end: d(3, 31),
    progress: 40,
    open: false,
  },

  // Epic 4: Analytics & Reporting
  {
    id: 40,
    text: 'Transaction History',
    type: 'summary',
    parent: 4,
    start: d(2, 2),
    end: d(3, 6),
    progress: 55,
    open: false,
  },
  {
    id: 41,
    text: 'Spending Analytics',
    type: 'summary',
    parent: 4,
    start: d(3, 2),
    end: d(4, 3),
    progress: 10,
    open: false,
  },
  {
    id: 42,
    text: 'Export & Reports',
    type: 'summary',
    parent: 4,
    start: d(3, 23),
    end: d(4, 25),
    progress: 0,
    open: false,
  },

  // Epic 5: Mobile Experience
  {
    id: 50,
    text: 'Push Notifications',
    type: 'summary',
    parent: 5,
    start: d(2, 16),
    end: d(3, 20),
    progress: 30,
    open: false,
  },
  {
    id: 51,
    text: 'Offline Mode',
    type: 'summary',
    parent: 5,
    start: d(3, 9),
    end: d(4, 17),
    progress: 5,
    open: false,
  },
  {
    id: 52,
    text: 'Accessibility (A11y)',
    type: 'summary',
    parent: 5,
    start: d(4, 6),
    end: d(5, 8),
    progress: 0,
    open: false,
  },

  // Epic 6: Infrastructure & DevOps
  {
    id: 60,
    text: 'CI/CD Pipeline',
    type: 'summary',
    parent: 6,
    start: d(1, 5),
    end: d(2, 7),
    progress: 95,
    open: false,
  },
  {
    id: 61,
    text: 'Monitoring & Alerting',
    type: 'summary',
    parent: 6,
    start: d(2, 2),
    end: d(3, 13),
    progress: 50,
    open: false,
  },
  {
    id: 62,
    text: 'Performance Optimization',
    type: 'summary',
    parent: 6,
    start: d(3, 16),
    end: d(5, 15),
    progress: 10,
    open: false,
  },
];

// ============================================================================
// User Stories, Tasks, Bugs (leaf tasks, parent=feature)
// ============================================================================
const workItems = [
  // ---- Feature 10: User Registration Flow ----
  {
    id: 100,
    text: 'Email verification flow',
    parent: 10,
    start: d(1, 5),
    end: d(1, 16),
    progress: 100,
    assigned: TEAM[0],
    labels: 'frontend,auth',
  },
  {
    id: 101,
    text: 'Phone number validation',
    parent: 10,
    start: d(1, 12),
    end: d(1, 23),
    progress: 100,
    assigned: TEAM[1],
    labels: 'backend,validation',
  },
  {
    id: 102,
    text: 'KYC document upload',
    parent: 10,
    start: d(1, 19),
    end: d(2, 4),
    progress: 85,
    assigned: TEAM[2],
    labels: 'frontend,compliance',
  },
  {
    id: 103,
    text: 'Registration API rate limiting',
    parent: 10,
    start: d(1, 26),
    end: d(2, 7),
    progress: 70,
    assigned: TEAM[3],
    labels: 'backend,security',
  },

  // ---- Feature 11: Profile Management ----
  {
    id: 110,
    text: 'Edit personal information',
    parent: 11,
    start: d(1, 19),
    end: d(1, 30),
    progress: 100,
    assigned: TEAM[4],
    labels: 'frontend',
  },
  {
    id: 111,
    text: 'Avatar upload & crop',
    parent: 11,
    start: d(1, 26),
    end: d(2, 6),
    progress: 80,
    assigned: TEAM[5],
    labels: 'frontend,media',
  },
  {
    id: 112,
    text: 'Address verification API',
    parent: 11,
    start: d(2, 2),
    end: d(2, 13),
    progress: 40,
    assigned: TEAM[6],
    labels: 'backend,integration',
  },
  {
    id: 113,
    text: 'Bug: Profile photo not saving on iOS',
    parent: 11,
    start: d(2, 9),
    end: d(2, 16),
    progress: 20,
    assigned: TEAM[5],
    labels: 'bug,ios',
  },
  {
    id: 114,
    text: 'Linked accounts management',
    parent: 11,
    start: d(2, 16),
    end: d(2, 28),
    progress: 0,
    assigned: TEAM[7],
    labels: 'frontend,backend',
  },

  // ---- Feature 12: Account Settings ----
  {
    id: 120,
    text: 'Notification preferences UI',
    parent: 12,
    start: d(2, 9),
    end: d(2, 20),
    progress: 60,
    assigned: TEAM[0],
    labels: 'frontend',
  },
  {
    id: 121,
    text: 'Language & region settings',
    parent: 12,
    start: d(2, 16),
    end: d(2, 27),
    progress: 45,
    assigned: TEAM[1],
    labels: 'frontend,i18n',
  },
  {
    id: 122,
    text: 'Account deletion workflow',
    parent: 12,
    start: d(2, 23),
    end: d(3, 6),
    progress: 30,
    assigned: TEAM[2],
    labels: 'backend,compliance',
  },
  {
    id: 123,
    text: 'Privacy settings dashboard',
    parent: 12,
    start: d(3, 2),
    end: d(3, 20),
    progress: 0,
    assigned: TEAM[3],
    labels: 'frontend,compliance',
  },

  // ---- Feature 20: Internal Transfers ----
  {
    id: 200,
    text: 'Own accounts transfer',
    parent: 20,
    start: d(1, 12),
    end: d(1, 23),
    progress: 100,
    assigned: TEAM[4],
    labels: 'backend,payments',
  },
  {
    id: 201,
    text: 'Same-bank beneficiary transfer',
    parent: 20,
    start: d(1, 19),
    end: d(2, 3),
    progress: 100,
    assigned: TEAM[5],
    labels: 'backend,payments',
  },
  {
    id: 202,
    text: 'Transfer confirmation screen',
    parent: 20,
    start: d(1, 26),
    end: d(2, 7),
    progress: 90,
    assigned: TEAM[6],
    labels: 'frontend,ux',
  },
  {
    id: 203,
    text: 'Spike: Instant payment protocol research',
    parent: 20,
    start: d(2, 2),
    end: d(2, 10),
    progress: 100,
    assigned: TEAM[7],
    labels: 'spike,research',
  },
  {
    id: 204,
    text: 'Transfer limits validation',
    parent: 20,
    start: d(2, 9),
    end: d(2, 21),
    progress: 30,
    assigned: TEAM[0],
    labels: 'backend,validation',
  },

  // ---- Feature 21: External Payments ----
  {
    id: 210,
    text: 'SWIFT transfer integration',
    parent: 21,
    start: d(2, 2),
    end: d(2, 20),
    progress: 70,
    assigned: TEAM[1],
    labels: 'backend,integration',
  },
  {
    id: 211,
    text: 'Bill payment scanning (OCR)',
    parent: 21,
    start: d(2, 9),
    end: d(2, 28),
    progress: 55,
    assigned: TEAM[2],
    labels: 'frontend,ai',
  },
  {
    id: 212,
    text: 'Payment scheduling',
    parent: 21,
    start: d(2, 23),
    end: d(3, 6),
    progress: 25,
    assigned: TEAM[3],
    labels: 'backend,scheduler',
  },
  {
    id: 213,
    text: 'Bug: Decimal rounding in foreign currency',
    parent: 21,
    start: d(2, 16),
    end: d(2, 25),
    progress: 40,
    assigned: TEAM[4],
    labels: 'bug,payments',
  },
  {
    id: 214,
    text: 'Payment receipt generation',
    parent: 21,
    start: d(3, 2),
    end: d(3, 13),
    progress: 0,
    assigned: TEAM[5],
    labels: 'backend,pdf',
  },

  // ---- Feature 22: Recurring Payments ----
  {
    id: 220,
    text: 'Recurring payment setup wizard',
    parent: 22,
    start: d(3, 2),
    end: d(3, 16),
    progress: 15,
    assigned: TEAM[6],
    labels: 'frontend,ux',
  },
  {
    id: 221,
    text: 'Payment schedule engine',
    parent: 22,
    start: d(3, 9),
    end: d(3, 27),
    progress: 10,
    assigned: TEAM[7],
    labels: 'backend,scheduler',
  },
  {
    id: 222,
    text: 'Recurring payment notifications',
    parent: 22,
    start: d(3, 23),
    end: d(4, 3),
    progress: 0,
    assigned: TEAM[0],
    labels: 'backend,notifications',
  },
  {
    id: 223,
    text: 'Modify/cancel recurring payments',
    parent: 22,
    start: d(3, 30),
    end: d(4, 10),
    progress: 0,
    assigned: TEAM[1],
    labels: 'frontend,backend',
  },

  // ---- Feature 30: Multi-Factor Authentication ----
  {
    id: 300,
    text: 'TOTP authenticator support',
    parent: 30,
    start: d(1, 5),
    end: d(1, 16),
    progress: 100,
    assigned: TEAM[2],
    labels: 'backend,security',
  },
  {
    id: 301,
    text: 'SMS OTP fallback',
    parent: 30,
    start: d(1, 12),
    end: d(1, 23),
    progress: 100,
    assigned: TEAM[3],
    labels: 'backend,security',
  },
  {
    id: 302,
    text: 'MFA enrollment UI',
    parent: 30,
    start: d(1, 19),
    end: d(2, 3),
    progress: 100,
    assigned: TEAM[4],
    labels: 'frontend,security',
  },
  {
    id: 303,
    text: 'Recovery codes generation',
    parent: 30,
    start: d(1, 26),
    end: d(2, 7),
    progress: 100,
    assigned: TEAM[5],
    labels: 'backend,security',
  },
  {
    id: 304,
    text: 'MFA bypass for trusted devices',
    parent: 30,
    start: d(2, 2),
    end: d(2, 14),
    progress: 100,
    assigned: TEAM[6],
    labels: 'backend,security',
  },

  // ---- Feature 31: Biometric Login ----
  {
    id: 310,
    text: 'Fingerprint authentication (Android)',
    parent: 31,
    start: d(1, 26),
    end: d(2, 7),
    progress: 100,
    assigned: TEAM[7],
    labels: 'mobile,android',
  },
  {
    id: 311,
    text: 'Face ID integration (iOS)',
    parent: 31,
    start: d(2, 2),
    end: d(2, 14),
    progress: 100,
    assigned: TEAM[0],
    labels: 'mobile,ios',
  },
  {
    id: 312,
    text: 'Biometric key storage',
    parent: 31,
    start: d(2, 9),
    end: d(2, 21),
    progress: 60,
    assigned: TEAM[1],
    labels: 'backend,security',
  },
  {
    id: 313,
    text: 'Bug: Biometric prompt not appearing after app update',
    parent: 31,
    start: d(2, 16),
    end: d(2, 28),
    progress: 30,
    assigned: TEAM[2],
    labels: 'bug,mobile',
  },
  {
    id: 314,
    text: 'Biometric fallback to PIN',
    parent: 31,
    start: d(2, 23),
    end: d(3, 6),
    progress: 20,
    assigned: TEAM[3],
    labels: 'mobile,security',
  },

  // ---- Feature 32: Session Management ----
  {
    id: 320,
    text: 'Active sessions dashboard',
    parent: 32,
    start: d(2, 16),
    end: d(2, 28),
    progress: 70,
    assigned: TEAM[4],
    labels: 'frontend,security',
  },
  {
    id: 321,
    text: 'Remote session revocation',
    parent: 32,
    start: d(2, 23),
    end: d(3, 6),
    progress: 50,
    assigned: TEAM[5],
    labels: 'backend,security',
  },
  {
    id: 322,
    text: 'Session timeout configuration',
    parent: 32,
    start: d(3, 2),
    end: d(3, 16),
    progress: 30,
    assigned: TEAM[6],
    labels: 'backend,settings',
  },
  {
    id: 323,
    text: 'Concurrent session limiting',
    parent: 32,
    start: d(3, 16),
    end: d(3, 31),
    progress: 0,
    assigned: TEAM[7],
    labels: 'backend,security',
  },

  // ---- Feature 40: Transaction History ----
  {
    id: 400,
    text: 'Transaction list with infinite scroll',
    parent: 40,
    start: d(2, 2),
    end: d(2, 14),
    progress: 100,
    assigned: TEAM[0],
    labels: 'frontend,performance',
  },
  {
    id: 401,
    text: 'Transaction search & filters',
    parent: 40,
    start: d(2, 9),
    end: d(2, 21),
    progress: 80,
    assigned: TEAM[1],
    labels: 'frontend,ux',
  },
  {
    id: 402,
    text: 'Transaction detail view',
    parent: 40,
    start: d(2, 16),
    end: d(2, 28),
    progress: 50,
    assigned: TEAM[2],
    labels: 'frontend',
  },
  {
    id: 403,
    text: 'Transaction categorization engine',
    parent: 40,
    start: d(2, 16),
    end: d(3, 6),
    progress: 25,
    assigned: TEAM[3],
    labels: 'backend,ai',
  },

  // ---- Feature 41: Spending Analytics ----
  {
    id: 410,
    text: 'Monthly spending chart',
    parent: 41,
    start: d(3, 2),
    end: d(3, 16),
    progress: 20,
    assigned: TEAM[4],
    labels: 'frontend,charts',
  },
  {
    id: 411,
    text: 'Category breakdown pie chart',
    parent: 41,
    start: d(3, 9),
    end: d(3, 23),
    progress: 10,
    assigned: TEAM[5],
    labels: 'frontend,charts',
  },
  {
    id: 412,
    text: 'Budget alerts & thresholds',
    parent: 41,
    start: d(3, 16),
    end: d(3, 31),
    progress: 5,
    assigned: TEAM[6],
    labels: 'backend,notifications',
  },
  {
    id: 413,
    text: 'Spending trends comparison',
    parent: 41,
    start: d(3, 23),
    end: d(4, 3),
    progress: 0,
    assigned: TEAM[7],
    labels: 'frontend,analytics',
  },

  // ---- Feature 42: Export & Reports ----
  {
    id: 420,
    text: 'PDF statement generation',
    parent: 42,
    start: d(3, 23),
    end: d(4, 3),
    progress: 0,
    assigned: TEAM[0],
    labels: 'backend,pdf',
  },
  {
    id: 421,
    text: 'CSV export for transactions',
    parent: 42,
    start: d(3, 30),
    end: d(4, 10),
    progress: 0,
    assigned: TEAM[1],
    labels: 'backend,export',
  },
  {
    id: 422,
    text: 'Tax report generation',
    parent: 42,
    start: d(4, 6),
    end: d(4, 25),
    progress: 0,
    assigned: TEAM[2],
    labels: 'backend,compliance',
  },

  // ---- Feature 50: Push Notifications ----
  {
    id: 500,
    text: 'FCM integration (Android)',
    parent: 50,
    start: d(2, 16),
    end: d(2, 28),
    progress: 70,
    assigned: TEAM[3],
    labels: 'mobile,android',
  },
  {
    id: 501,
    text: 'APNs integration (iOS)',
    parent: 50,
    start: d(2, 23),
    end: d(3, 6),
    progress: 50,
    assigned: TEAM[4],
    labels: 'mobile,ios',
  },
  {
    id: 502,
    text: 'Notification templates engine',
    parent: 50,
    start: d(3, 2),
    end: d(3, 13),
    progress: 15,
    assigned: TEAM[5],
    labels: 'backend,notifications',
  },
  {
    id: 503,
    text: 'Rich notification with actions',
    parent: 50,
    start: d(3, 9),
    end: d(3, 20),
    progress: 0,
    assigned: TEAM[6],
    labels: 'mobile,ux',
  },

  // ---- Feature 51: Offline Mode ----
  {
    id: 510,
    text: 'Spike: Offline-first architecture evaluation',
    parent: 51,
    start: d(3, 9),
    end: d(3, 18),
    progress: 10,
    assigned: TEAM[7],
    labels: 'spike,architecture',
  },
  {
    id: 511,
    text: 'Local data sync engine',
    parent: 51,
    start: d(3, 16),
    end: d(4, 3),
    progress: 5,
    assigned: TEAM[0],
    labels: 'mobile,sync',
  },
  {
    id: 512,
    text: 'Conflict resolution strategy',
    parent: 51,
    start: d(3, 30),
    end: d(4, 10),
    progress: 0,
    assigned: TEAM[1],
    labels: 'backend,sync',
  },
  {
    id: 513,
    text: 'Offline transaction queue',
    parent: 51,
    start: d(4, 6),
    end: d(4, 17),
    progress: 0,
    assigned: TEAM[2],
    labels: 'mobile,payments',
  },

  // ---- Feature 52: Accessibility ----
  {
    id: 520,
    text: 'Screen reader compatibility audit',
    parent: 52,
    start: d(4, 6),
    end: d(4, 17),
    progress: 0,
    assigned: TEAM[3],
    labels: 'a11y,audit',
  },
  {
    id: 521,
    text: 'Keyboard navigation support',
    parent: 52,
    start: d(4, 13),
    end: d(4, 25),
    progress: 0,
    assigned: TEAM[4],
    labels: 'frontend,a11y',
  },
  {
    id: 522,
    text: 'High contrast theme',
    parent: 52,
    start: d(4, 20),
    end: d(5, 1),
    progress: 0,
    assigned: TEAM[5],
    labels: 'frontend,a11y',
  },
  {
    id: 523,
    text: 'Voice command integration',
    parent: 52,
    start: d(4, 27),
    end: d(5, 8),
    progress: 0,
    assigned: TEAM[6],
    labels: 'mobile,a11y',
  },

  // ---- Feature 60: CI/CD Pipeline ----
  {
    id: 600,
    text: 'Build pipeline configuration',
    parent: 60,
    start: d(1, 5),
    end: d(1, 16),
    progress: 100,
    assigned: TEAM[7],
    labels: 'devops,ci',
  },
  {
    id: 601,
    text: 'Automated test suite integration',
    parent: 60,
    start: d(1, 12),
    end: d(1, 26),
    progress: 100,
    assigned: TEAM[0],
    labels: 'devops,testing',
  },
  {
    id: 602,
    text: 'Staging environment deployment',
    parent: 60,
    start: d(1, 19),
    end: d(2, 3),
    progress: 100,
    assigned: TEAM[1],
    labels: 'devops,deploy',
  },
  {
    id: 603,
    text: 'Production blue-green deployment',
    parent: 60,
    start: d(1, 26),
    end: d(2, 7),
    progress: 80,
    assigned: TEAM[2],
    labels: 'devops,deploy',
  },

  // ---- Feature 61: Monitoring & Alerting ----
  {
    id: 610,
    text: 'APM integration (DataDog)',
    parent: 61,
    start: d(2, 2),
    end: d(2, 14),
    progress: 90,
    assigned: TEAM[3],
    labels: 'devops,monitoring',
  },
  {
    id: 611,
    text: 'Error tracking (Sentry)',
    parent: 61,
    start: d(2, 9),
    end: d(2, 21),
    progress: 75,
    assigned: TEAM[4],
    labels: 'devops,monitoring',
  },
  {
    id: 612,
    text: 'Custom alerting rules',
    parent: 61,
    start: d(2, 16),
    end: d(3, 2),
    progress: 35,
    assigned: TEAM[5],
    labels: 'devops,alerting',
  },
  {
    id: 613,
    text: 'Health check dashboard',
    parent: 61,
    start: d(2, 23),
    end: d(3, 13),
    progress: 15,
    assigned: TEAM[6],
    labels: 'devops,dashboard',
  },

  // ---- Feature 62: Performance Optimization ----
  {
    id: 620,
    text: 'API response caching (Redis)',
    parent: 62,
    start: d(3, 16),
    end: d(3, 31),
    progress: 20,
    assigned: TEAM[7],
    labels: 'backend,performance',
  },
  {
    id: 621,
    text: 'Database query optimization',
    parent: 62,
    start: d(3, 23),
    end: d(4, 10),
    progress: 10,
    assigned: TEAM[0],
    labels: 'backend,database',
  },
  {
    id: 622,
    text: 'CDN setup for static assets',
    parent: 62,
    start: d(4, 6),
    end: d(4, 17),
    progress: 0,
    assigned: TEAM[1],
    labels: 'devops,performance',
  },
  {
    id: 623,
    text: 'Load testing & benchmarking',
    parent: 62,
    start: d(4, 13),
    end: d(5, 1),
    progress: 0,
    assigned: TEAM[2],
    labels: 'devops,testing',
  },
  {
    id: 624,
    text: 'Image optimization pipeline',
    parent: 62,
    start: d(4, 27),
    end: d(5, 15),
    progress: 0,
    assigned: TEAM[3],
    labels: 'frontend,performance',
  },
];

// ============================================================================
// All tasks combined
// ============================================================================
export const tasks = [...epics, ...features, ...workItems];

// ============================================================================
// Dependencies (links)
// e2s = end-to-start dependency
// ============================================================================
export const links = [
  // Registration flow dependencies
  { id: 1, source: 100, target: 101, type: 'e2s' },
  { id: 2, source: 101, target: 102, type: 'e2s' },
  { id: 3, source: 102, target: 103, type: 'e2s' },

  // Profile depends on registration
  { id: 4, source: 103, target: 110, type: 'e2s' },

  // MFA flow
  { id: 5, source: 300, target: 301, type: 'e2s' },
  { id: 6, source: 301, target: 302, type: 'e2s' },
  { id: 7, source: 302, target: 303, type: 'e2s' },
  { id: 8, source: 303, target: 304, type: 'e2s' },

  // Biometric depends on MFA
  { id: 9, source: 304, target: 310, type: 'e2s' },
  { id: 10, source: 310, target: 311, type: 'e2s' },

  // Internal transfers flow
  { id: 11, source: 200, target: 201, type: 'e2s' },
  { id: 12, source: 201, target: 202, type: 'e2s' },
  { id: 13, source: 203, target: 204, type: 'e2s' },

  // External payments depend on internal transfers
  { id: 14, source: 204, target: 210, type: 'e2s' },

  // SWIFT -> Bill pay -> Scheduling
  { id: 15, source: 210, target: 211, type: 'e2s' },
  { id: 16, source: 211, target: 212, type: 'e2s' },

  // CI/CD pipeline flow
  { id: 17, source: 600, target: 601, type: 'e2s' },
  { id: 18, source: 601, target: 602, type: 'e2s' },
  { id: 19, source: 602, target: 603, type: 'e2s' },

  // Monitoring depends on CI/CD
  { id: 20, source: 603, target: 610, type: 'e2s' },

  // Notifications: Android -> iOS -> templates
  { id: 21, source: 500, target: 501, type: 'e2s' },
  { id: 22, source: 501, target: 502, type: 'e2s' },
  { id: 23, source: 502, target: 503, type: 'e2s' },

  // Offline spike -> local sync
  { id: 24, source: 510, target: 511, type: 'e2s' },
  { id: 25, source: 511, target: 512, type: 'e2s' },
  { id: 26, source: 512, target: 513, type: 'e2s' },

  // Analytics flow
  { id: 27, source: 400, target: 401, type: 'e2s' },
  { id: 28, source: 403, target: 410, type: 'e2s' },
];
